const products = [
    { id: 1, image: "../asset/backpack.JPG", name: "Backpack", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200}, 
    { id: 2, image: "../asset/backpack1.JPG", name: "Backpack1", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200},
    { id: 3, image: "../asset/backpack2.JPG", name: "Backpack2", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200},
    { id: 4, image: "../asset/backpack3.JPG", name: "Backpack3", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200}, 
    { id: 5, image: "../asset/backpack4.JPG", name: "Backpack4", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200},
    { id: 6, image: "../asset/toiletriesbag1.JPG", name: "Toiletriesbag1", desc: "Many desktop publishing packages and web\npage editors now use Lorem Ipsum as their\ndefault model text, and a search for 'lorem\nipsum' will \nuncover many web sites still in their\ninfancy.", price: 200},
    { id: 7, image: "../asset/toiletriesbag2.JPG", name: "Toiletriesbag2", desc: "Many desktop publishing packages and web\n page editors now use Lorem Ipsum as their\n default model text, and a search for 'lorem<br> ipsum' will <br>uncover many web sites still in their<br> infancy.", price: 200}, 
    { id: 8, image: "../asset/toiletriesbag3.JPG", name: "Toiletriesbag3", desc: "Many desktop publishing packages and web\n page editors now use Lorem Ipsum as their\n default model text, and a search for 'lorem<br> ipsum' will <br>uncover many web sites still in their<br> infancy.", price: 200},
    { id: 9, image: "../asset/toiletriesbag4.JPG", name: "Toiletriesbag4", desc: "Many desktop publishing packages and web\n page editors now use Lorem Ipsum as their\n default model text, and a search for 'lorem<br> ipsum' will <br>uncover many web sites still in their<br> infancy.", price: 200},
    { id: 10,image: "../asset/toiletriesbag5.JPG", name: "Toiletriesbag5", desc: "Many desktop publishing packages and web\n page editors now use Lorem Ipsum as their\n default model text, and a search for 'lorem<br> ipsum' will <br>uncover many web sites still in their<br> infancy.", price: 200},
    { id: 11, image: "../asset/toiletriesbag6.JPG", name: "Toiletriesbag6", desc: "Many desktop publishing packages and web\n page editors now use Lorem Ipsum as their\n default model text, and a search for 'lorem<br> ipsum' will <br>uncover many web sites still in their<br> infancy.", price: 200}
];